<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OTUS_Homework_SolarSystem_2\OTUS_Homework_SolarSystem_2.csproj" />
    <ProjectReference Include="..\OTUS_Homework_SolarSystem_3\OTUS_Homework_SolarSystem_3.csproj" />
  </ItemGroup>

</Project>
